import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
import Header from '@/components/structural/Header';
import Footer from '@/components/structural/Footer';
import Heading from '@/components/typography/Heading';

const Home: NextPage = function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Heading>Hello</Heading>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
