import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Heading } from '@chakra-ui/react';
import styles from '@/styles/Home.module.css';

const Home: NextPage = function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h1" size="4xl" mb="4">
          Hello World!
        </Heading>
      </main>

      <footer className={styles.footer}>
        Hello Footer Text
      </footer>
    </div>
  );
};

export default Home;
